apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: petclinic-initial-run
spec:
  params:
    - name: deployment-name
      value: petclinic
    - name: git-url
      value: 'https://github.com/pittar/spring-petclinic.git'
    - name: git-revision
      value: master
    - name: IMAGE
      value: image-registry.openshift-image-registry.svc:5000/txt137-openliberty-getting-started/gettingstarted-guide
    - name: maven-image
      value: image-registry.openshift-image-registry.svc:5000/openshift/ubi8-openjdk-11
      #value: image-registry.openshift-image-registry.svc:5000/txt137-openliberty-getting-started/openjdk-11
  pipelineRef:
    name: build-and-deploy
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: workspace
    - name: maven-settings
      emptyDir: {}
      
